### ISSUE TITLE
Utilize Netlify CMS collections for adding content to homepage

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#107]
currently, the styling for the netlify CMS "cats" field is all one line. Please change this to a larger sized text field

**Comment by LayaTaal** [comment]
@EvaRuthM I changed the title for this from `fix "cats" field on netlify CMS` since this is part of a larger issue.

There are two ways Netlify CMS can handle data - Pages, and Collections. For the homepage, I think we really want to utilize the Collection feature so that we can pull those "posts" into the homepage dynamically.

The dynamic functionality is already setup, we just need to modify Netlify a bit to be able to create these for us. More information on that is [here](https://www.netlifycms.org/docs/configuration-options/#collections).
