### ISSUE TITLE
Downloaded data bug

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#171]
For some reason, the data that is downloaded when one clicks on "download the data" on the netlify site does not give us the same version as we get now (we want to see the expanded data set, but filtered; now only get a data set that reflects what the charts show)

**Comment by nholden** [comment]
Good catch, @EvaRuthM! Thanks for opening up this issue.

From [`/data/datasets.js`](https://github.com/texas-justice-initiative/website-nextjs/blob/master/data/datasets.js), it looks like we're currently loading the data for the charts and for CSV downloads from the JSON data in `compressed` URLs, when we should be loading the data for CSV downloads from the CSV data in `full` URLs. [Here's an example](https://github.com/texas-justice-initiative/website-nextjs/blob/b84ef1202052a96fa89920bab86f4e6732b248c1/data/datasets.js#L14-L17) of those two URLs for the "Deaths in Custody" dataset.

In the short term, we can get started on a fix grabbing CSV download data from the `full` URLs.

A longer term solution may be to consider storing this data differently. I had mentioned to @LayaTaal that storing this data in a relational database instead of in JSON or CSVs might allow us to more easily query for just the data we need. It would require some more infrastructure to set up, but I think it would lead to faster page loads and more maintainable data, especially as the datasets continue to grow. @laconc: do you know if we've considered other ways to store and access these datasets in the past?

**Comment by laconc** [comment]
No, but I wasn't involved with TJI for a period. Setting up a relational database would be relatively simple. Since we're moving towards a fully static site, I believe that any code to access a database would be exposed through the browser, making it a potential attack vector. Perhaps, that's not such a big deal since none of the data is sensitive and we can limit users to only read from it. Front-end website development isn't my strong suit so please let me know if I've misunderstood the situation.

**Comment by nholden** [comment]
Thanks, @laconc! That makes sense to me. I agree that we'd want to be careful about what we expose the the browser. I wonder if there's a service that would let us expose a handful predefined, read-only queries to a database via an API that would be safe to use on the front end.

I did some research into how the download button works on [the current site](http://texasjusticeinitiative.org/data/). Here's how it works:
- Each time the user changes the dataset from the dropdown menu, the browser downloads the [`compressed`](https://github.com/texas-justice-initiative/website/blob/69dd7e2ca855b086763b3adac93dcec9d75f607c/js/tji-datasets-explore.js#L375) and then the [`complete`](https://github.com/texas-justice-initiative/website/blob/69dd7e2ca855b086763b3adac93dcec9d75f607c/js/tji-datasets-explore.js#L381) versions of the data.
- The browser uses the `compressed` version to render the charts relatively quickly and then downloads the `complete` version in the background, [enabling the "Download" button when the `complete` download completes](https://github.com/texas-justice-initiative/website/blob/69dd7e2ca855b086763b3adac93dcec9d75f607c/js/tji-datasets-explore.js#L402-L404).
- When the user clicks the download button, the browser looks at the indicies of the data points in the `compressed` version to [determine which rows of the `complete` version to include in the CSV](https://github.com/texas-justice-initiative/website/blob/69dd7e2ca855b086763b3adac93dcec9d75f607c/js/tji-datasets-explore.js#L850-L852) and starts the download.

When I have more time, I can take a stab at implementing something similar in the new site. Of course, if someone else has time before me and feels like taking this on, please do!
