### ISSUE TITLE
Create donation success page

### ISSUE THREAD

**Issue by LayaTaal** [texas-justice-initiative/website-nextjs#201]
Currently when a users completes a PayPal donation it sends them back to the review form on the donation page. It would be nice to send them to a success page.

**Comment by Antrikshy** [comment]
I was poking around your codebase and might be able to tackle this one. It's a bit tough to figure out how the PayPal stuff works in a dev environment.

Can you verify if [this `returnUrl` value](https://github.com/texas-justice-initiative/website-nextjs/blob/ade6a0c56f64d28eec5a723697daac35c4ad45e5/components/forms/PaypalButton.js#L67) is something you specify in your PayPal settings as an owner? Is the goal of this task to design a whole new donation-thank-you page, independent from the rest of the code, that you then put into your PayPal settings?

**Comment by nholden** [comment]
👋  Hi, @Antrikshy! Thanks so much for looking into this, and sorry we didn't notice your comment until now!

I looked into it, and I think we mislabeled this one as a "good first issue." We don't have PayPal well configured for local development, and we're using [this older PayPal integration](https://developer.paypal.com/docs/archive/checkout/integrate). Plus, to test it out, we'd need to set you up with some PayPal sandbox credentials.

All that to say: our bad for labeling this one as a "good first issue" when it actually required more context and access than is reasonable for a new contributor. I took a stab at addressing this one in https://github.com/texas-justice-initiative/website-nextjs/pull/482.

If you're still interested in helping out, https://github.com/texas-justice-initiative/website-nextjs/issues/351 details a few layout issues we noticed that we could use some help with. I'd recommend getting started by addressing just one of the bugs mentioned there and opening a small PR. We'd also love contributions that improve our documentation and the local development experience so that it's easier to onboard newcomers.

Thanks again for your interest in helping out! Please let me know if you have any questions. 😄 

cc @EvaRuthM
