### ISSUE TITLE
change order of new items in Netlify

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#428]
Currently, when we add a new item to the newsfeed in Netlify, the new item is added at the bottom of the growing list of newsfeed items. 
Ideally, we would like for the new items to default to go on the top of the list, for both the Newsfeed the cards on the new explore landing page.

**Comment by nholden** [comment]
There's no way to do this in Netlify CMS currently. It looks like [others](https://github.com/netlify/netlify-cms/issues/3270) have bumped into this same problem, so I opened [a pull request](https://github.com/netlify/netlify-cms/pull/4465) to add a configuration option to lists so that new items are added to the top. More to come!
