### ISSUE TITLE
remove photo requirement for alumni on "about us"

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#587]
We would like to remove the photos and show names only for TJI Alumni but the CMS gives an error when the photos are removed. Please change the CMS so that we can have just names shown for TJI Alumni (on "About Us" page).

**Comment by nholden** [comment]
Should be all set!

While I was here, I noticed that some of the headshots for our current volunteers were distorted because we force the photos to load as squares but some of the original images had different aspect ratios. I thought I had set up Cloudinary to make it easy to crop those images as squares when we upload them, but it didn't work like I expected.

I cropped all the headshots manually and re-uploaded them, so they're looking better! Until we we figure out how to get Cloudinary to help us with this, we should ask new volunteers to send us square headshots (or ask me to crop them).

### Before

![Screen Shot 2021-04-20 at 7 40 59 PM](https://user-images.githubusercontent.com/7942714/115490893-d2399700-a213-11eb-8c16-54cdee3010bd.png)

### After

![Screen Shot 2021-04-20 at 8 02 45 PM](https://user-images.githubusercontent.com/7942714/115490899-d5cd1e00-a213-11eb-967f-6e34db90b8fe.png)
